import React from "react";
import FakeDb from "../custom/fakedb";
const dummyData = [
  {
    id: "1",
    productName: "Trello Course",
    price: 100000,
    description: "10 day intensive course, learn to use trello.",
    image: "https://image.flaticon.com/icons/png/128/174/174874.png",
  },
  {
    id: "2",
    productName: "MS Excel for data engineer",
    price: 100000,
    description: "Learn using MS Excel for data gathering and manipulation.",
    image: "https://image.flaticon.com/icons/png/128/888/888850.png",
  },
  {
    id: "3",
    productName: "Basic Adobe Illustrator",
    price: 100000,
    description: "Learn basic vector design using adobe illustrator.",
    image: "https://image.flaticon.com/icons/png/128/552/552222.png",
  },
  {
    id: "4",
    productName: "Present Like a Pro",
    price: 100000,
    description: "Learn how to compose best presentation for any needs.",
    image: "https://image.flaticon.com/icons/png/128/888/888874.png",
  },
  {
    id: "5",
    productName: "Photoshop for photographers",
    price: 100000,
    description: "Learn how edit photo using adobe photoshop.",
    image: "https://image.flaticon.com/icons/png/128/552/552220.png",
  },
  {
    id: "6",
    productName: "Build Instagram Business",
    price: 100000,
    description: "Learn how create online store using Instagram.",
    image: "https://image.flaticon.com/icons/svg/1409/1409946.svg",
  },
  {
    id: "7",
    productName: "Trello Course",
    price: 100000,
    description: "10 day intensive course, learn to use trello.",
    image: "https://image.flaticon.com/icons/png/128/174/174874.png",
  },
  {
    id: "8",
    productName: "MS Excel for data engineer",
    price: 100000,
    description: "Learn using MS Excel for data gathering and manipulation.",
    image: "https://image.flaticon.com/icons/png/128/888/888850.png",
  },
  {
    id: "9",
    productName: "Basic Adobe Illustrator",
    price: 100000,
    description: "Learn basic vector design using adobe illustrator.",
    image: "https://image.flaticon.com/icons/png/128/552/552222.png",
  },
  {
    id: "10",
    productName: "Present Like a Pro",
    price: 100000,
    description: "Learn how to compose best presentation for any needs.",
    image: "https://image.flaticon.com/icons/png/128/888/888874.png",
  },
  {
    id: "11",
    productName: "Photoshop for photographers",
    price: 100000,
    description: "Learn how edit photo using adobe photoshop.",
    image: "https://image.flaticon.com/icons/png/128/552/552220.png",
  },
  {
    id: "12",
    productName: "Build Instagram Business",
    price: 100000,
    description: "Learn how create online store using Instagram.",
    image: "https://image.flaticon.com/icons/svg/1409/1409946.svg",
  },
  {
    id: "13",
    productName: "MS Excel for data engineer",
    price: 100000,
    description: "Learn using MS Excel for data gathering and manipulation.",
    image: "https://image.flaticon.com/icons/png/128/888/888850.png",
  },
  {
    id: "14",
    productName: "Basic Adobe Illustrator",
    price: 100000,
    description: "Learn basic vector design using adobe illustrator.",
    image: "https://image.flaticon.com/icons/png/128/552/552222.png",
  },
  {
    id: "15",
    productName: "Photoshop for photographers",
    price: 100000,
    description: "Learn how edit photo using adobe photoshop.",
    image: "https://image.flaticon.com/icons/png/128/552/552220.png",
  },
  {
    id: "16",
    productName: "Build Instagram Business",
    price: 100000,
    description: "Learn how create online store using Instagram.",
    image: "https://image.flaticon.com/icons/svg/1409/1409946.svg",
  },
  {
    id: "17",
    productName: "Present Like a Pro",
    price: 100000,
    description: "Learn how to compose best presentation for any needs.",
    image: "https://image.flaticon.com/icons/png/128/888/888874.png",
  },
  {
    id: "18",
    productName: "Photoshop for photographers",
    price: 100000,
    description: "Learn how edit photo using adobe photoshop.",
    image: "https://image.flaticon.com/icons/png/128/552/552220.png",
  },
  {
    id: "19",
    productName: "Build Instagram Business",
    price: 100000,
    description: "Learn how create online store using Instagram.",
    image: "https://image.flaticon.com/icons/svg/1409/1409946.svg",
  },
  {
    id: "20",
    productName: "Trello Course",
    price: 100000,
    description: "10 day intensive course, learn to use trello.",
    image: "https://image.flaticon.com/icons/png/128/174/174874.png",
  },
  {
    id: "21",
    productName: "MS Excel for data engineer",
    price: 100000,
    description: "Learn using MS Excel for data gathering and manipulation.",
    image: "https://image.flaticon.com/icons/png/128/888/888850.png",
  },
  {
    id: "22",
    productName: "Basic Adobe Illustrator",
    price: 100000,
    description: "Learn basic vector design using adobe illustrator.",
    image: "https://image.flaticon.com/icons/png/128/552/552222.png",
  },
  {
    id: "23",
    productName: "Present Like a Pro",
    price: 100000,
    description: "Learn how to compose best presentation for any needs.",
    image: "https://image.flaticon.com/icons/png/128/888/888874.png",
  },
  {
    id: "24",
    productName: "Photoshop for photographers",
    price: 100000,
    description: "Learn how edit photo using adobe photoshop.",
    image: "https://image.flaticon.com/icons/png/128/552/552220.png",
  },
  {
    id: "25",
    productName: "Build Instagram Business",
    price: 100000,
    description: "Learn how create online store using Instagram.",
    image: "https://image.flaticon.com/icons/svg/1409/1409946.svg",
  },
  {
    id: "26",
    productName: "MS Excel for data engineer",
    price: 100000,
    description: "Learn using MS Excel for data gathering and manipulation.",
    image: "https://image.flaticon.com/icons/png/128/888/888850.png",
  },
  {
    id: "27",
    productName: "Basic Adobe Illustrator",
    price: 100000,
    description: "Learn basic vector design using adobe illustrator.",
    image: "https://image.flaticon.com/icons/png/128/552/552222.png",
  },
  {
    id: "28",
    productName: "Photoshop for photographers",
    price: 100000,
    description: "Learn how edit photo using adobe photoshop.",
    image: "https://image.flaticon.com/icons/png/128/552/552220.png",
  },
  {
    id: "29",
    productName: "Build Instagram Business",
    price: 100000,
    description: "Learn how create online store using Instagram.",
    image: "https://image.flaticon.com/icons/svg/1409/1409946.svg",
  },
  {
    id: "30",
    productName: "Trello Course",
    price: 100000,
    description: "10 day intensive course, learn to use trello.",
    image: "https://image.flaticon.com/icons/png/128/174/174874.png",
  },
];

const productData = (slice, page) => FakeDb(dummyData, slice, page);

export default productData;
